package vista;

import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javaswingdev.message.MessageDialog;
import libreriaproyecto.NuevoServicio;
import negocio.ServiciosControl;

public class Editar extends javax.swing.JFrame 
{
    private int id;
    private String nombreAnt;
    private final ServiciosControl CONTROL;
    
    public Editar() 
    {
        initComponents();
        CONTROL = new ServiciosControl();
        
        setLocation(360, 100);
        jPanel2.setVisible(false);
    }
    
    public void Variables(String id, String nombre, String nombreAnt, String duracion, String costo, String descuento, String tipo)
    {
        this.id = Integer.parseInt(id);
        txtNombreS.setText(nombre);
        this.nombreAnt = nombreAnt;
        txtDuracion.setText(duracion);
        txtCosto.setText(costo.substring(1));
        txtDescuento.setText(descuento.replace("%", ""));
        txtTipo.setText(tipo);
        Rutas(nombre);
    }
    
    private void Limpiar()
    {
        txtNombreS.setText("");
        txtDuracion.setText("");
        txtCosto.setText("");
        txtDescuento.setText("");
        txtTipo.setText("");
    }
    
    private void Llenar()
    {
        txtNombreS.setText("Nombre");
        txtDuracion.setText("Duración");
        txtCosto.setText("Costo");
        txtDescuento.setText("Descuento");
        txtTipo.setText("Tipo");
    }
    
    private void Desaparecer()
    {
        txtNombreS.setVisible(false);
        txtDuracion.setVisible(false);
        txtCosto.setVisible(false);
        txtDescuento.setVisible(false);
        txtTipo.setVisible(false);
    }
    
    private void Aparecer()
    {
        txtNombreS.setVisible(true);
        txtDuracion.setVisible(true);
        txtCosto.setVisible(true);
        txtDescuento.setVisible(true);
        txtTipo.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtRuta1 = new javax.swing.JTextField();
        txtRuta2 = new javax.swing.JTextField();
        txtRuta3 = new javax.swing.JTextField();
        txtRuta4 = new javax.swing.JTextField();
        txtRuta5 = new javax.swing.JTextField();
        txtRuta6 = new javax.swing.JTextField();
        txtRuta7 = new javax.swing.JTextField();
        txtRuta8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreS = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnEditarCarr = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRuta1.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta1.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta1.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta1.setText("Ruta 1");
        txtRuta1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta1FocusLost(evt);
            }
        });
        txtRuta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta1MouseClicked(evt);
            }
        });
        txtRuta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 540, 35));

        txtRuta2.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta2.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta2.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta2.setText("Ruta 2");
        txtRuta2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta2FocusLost(evt);
            }
        });
        txtRuta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta2MouseClicked(evt);
            }
        });
        txtRuta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 540, 35));

        txtRuta3.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta3.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta3.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta3.setText("Ruta 3");
        txtRuta3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta3FocusLost(evt);
            }
        });
        txtRuta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta3MouseClicked(evt);
            }
        });
        txtRuta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta3ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 540, 35));

        txtRuta4.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta4.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta4.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta4.setText("Ruta 4");
        txtRuta4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta4FocusLost(evt);
            }
        });
        txtRuta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta4MouseClicked(evt);
            }
        });
        txtRuta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta4ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, 540, 35));

        txtRuta5.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta5.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta5.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta5.setText("Ruta 5");
        txtRuta5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta5FocusLost(evt);
            }
        });
        txtRuta5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta5MouseClicked(evt);
            }
        });
        txtRuta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta5ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 540, 35));

        txtRuta6.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta6.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta6.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta6.setText("Ruta 6");
        txtRuta6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta6FocusLost(evt);
            }
        });
        txtRuta6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta6MouseClicked(evt);
            }
        });
        txtRuta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta6ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 245, 540, 35));

        txtRuta7.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta7.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta7.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta7.setText("Ruta 7");
        txtRuta7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta7FocusLost(evt);
            }
        });
        txtRuta7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta7MouseClicked(evt);
            }
        });
        txtRuta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta7ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 540, 35));

        txtRuta8.setBackground(new java.awt.Color(191, 166, 161, 110));
        txtRuta8.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txtRuta8.setForeground(new java.awt.Color(98, 88, 88));
        txtRuta8.setText("Ruta 8");
        txtRuta8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRuta8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuta8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuta8FocusLost(evt);
            }
        });
        txtRuta8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuta8MouseClicked(evt);
            }
        });
        txtRuta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuta8ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 335, 540, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 580, 405));

        jPanel1.setBackground(new java.awt.Color(207, 189, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 920, 10));

        jLabel3.setBackground(new java.awt.Color(207, 189, 186));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 88, 88));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Editar Servicio");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 110));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 120));

        txtNombreS.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtNombreS.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtNombreS.setForeground(new java.awt.Color(98, 88, 88));
        txtNombreS.setText("Nombre");
        txtNombreS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNombreS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreSFocusLost(evt);
            }
        });
        txtNombreS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreSMouseClicked(evt);
            }
        });
        txtNombreS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 540, 45));

        txtDuracion.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtDuracion.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtDuracion.setForeground(new java.awt.Color(98, 88, 88));
        txtDuracion.setText("Duración");
        txtDuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDuracion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDuracionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDuracionFocusLost(evt);
            }
        });
        txtDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDuracionMouseClicked(evt);
            }
        });
        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 540, 45));

        txtCosto.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtCosto.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtCosto.setForeground(new java.awt.Color(98, 88, 88));
        txtCosto.setText("Costo");
        txtCosto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCosto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCostoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCostoFocusLost(evt);
            }
        });
        txtCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCostoMouseClicked(evt);
            }
        });
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 540, 45));

        txtDescuento.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtDescuento.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(98, 88, 88));
        txtDescuento.setText("Descuento");
        txtDescuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusLost(evt);
            }
        });
        txtDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescuentoMouseClicked(evt);
            }
        });
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 540, 45));

        txtTipo.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtTipo.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(98, 88, 88));
        txtTipo.setText("Tipo");
        txtTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoFocusLost(evt);
            }
        });
        txtTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTipoMouseClicked(evt);
            }
        });
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 540, 45));

        btnCancelar.setBackground(new java.awt.Color(225, 214, 212));
        btnCancelar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(98, 88, 88));
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 190, -1));

        btnEditarCarr.setBackground(new java.awt.Color(225, 214, 212));
        btnEditarCarr.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnEditarCarr.setForeground(new java.awt.Color(98, 88, 88));
        btnEditarCarr.setText("Editar Carrusel");
        btnEditarCarr.setFocusPainted(false);
        btnEditarCarr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCarrMouseClicked(evt);
            }
        });
        jPanel1.add(btnEditarCarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 210, -1));

        btnGuardar.setBackground(new java.awt.Color(225, 214, 212));
        btnGuardar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(98, 88, 88));
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusPainted(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, 190, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 920, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreSFocusGained
        if(txtNombreS.getText().equals("Nombre"))
        {
            txtNombreS.setText("");
            txtNombreS.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtNombreSFocusGained

    private void txtNombreSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreSFocusLost
        if(txtNombreS.getText().isEmpty())
        {
            txtNombreS.setText("Nombre");
            txtNombreS.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtNombreSFocusLost

    private void txtNombreSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSMouseClicked

    private void txtNombreSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSActionPerformed

    private void txtDuracionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuracionFocusGained
        if(txtDuracion.getText().equals("Duración"))
        {
            txtDuracion.setText("");
            txtDuracion.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDuracionFocusGained

    private void txtDuracionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuracionFocusLost
        if(txtDuracion.getText().isEmpty())
        {
            txtDuracion.setText("Duración");
            txtDuracion.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDuracionFocusLost

    private void txtDuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDuracionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionMouseClicked

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void txtCostoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostoFocusGained
        if(txtCosto.getText().equals("Costo"))
        {
            txtCosto.setText("");
            txtCosto.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtCostoFocusGained

    private void txtCostoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostoFocusLost
        if(txtCosto.getText().isEmpty())
        {
            txtCosto.setText("Costo");
            txtCosto.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtCostoFocusLost

    private void txtCostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCostoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoMouseClicked

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtDescuentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusGained
        if(txtDescuento.getText().equals("Descuento"))
        {
            txtDescuento.setText("");
            txtDescuento.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDescuentoFocusGained

    private void txtDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusLost
        if(txtDescuento.getText().isEmpty())
        {
            txtDescuento.setText("Descuento");
            txtDescuento.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDescuentoFocusLost

    private void txtDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescuentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoMouseClicked

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusGained
        if(txtTipo.getText().equals("Tipo"))
        {
            txtTipo.setText("");
            txtTipo.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtTipoFocusGained

    private void txtTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusLost
        if(txtTipo.getText().isEmpty())
        {
            txtTipo.setText("Tipo");
            txtTipo.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtTipoFocusLost

    private void txtTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoMouseClicked

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        Limpiar();
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEditarCarrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCarrMouseClicked
        NuevoServicio obn = new NuevoServicio();
        List<JTextField> textFields = Arrays.asList(txtRuta1, txtRuta2, txtRuta3, txtRuta4, txtRuta5, txtRuta6, txtRuta7, txtRuta8);
        String resp;
        MessageDialog OptionPane = new MessageDialog(this);
              
        if(!txtNombreS.getText().isEmpty() && !txtNombreS.getText().equals("Nombre"))
            if(obn.validarNombre(txtNombreS.getText()) == false)
            {
                OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                txtNombreS.setText("");
            }
            else
                if(!txtDuracion.getText().isEmpty() && !txtDuracion.getText().equals("Duración"))
                    if(obn.validarDuracion(txtDuracion.getText()) == false)
                    {
                        OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                        txtDuracion.setText("");
                    }
                    else
                        if(!txtCosto.getText().isEmpty() && !txtCosto.getText().equals("Costo"))
                                if(!txtDescuento.getText().isEmpty() && !txtDescuento.getText().equals("Descuento"))
                                    if(obn.validarDescuento(txtDescuento.getText()) == false)
                                    {
                                        OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                                        txtDescuento.setText("");
                                    }
                                    else
                                        if(!txtTipo.getText().isEmpty() && !txtTipo.getText().equals("Tipo"))
                                            if(obn.validarTipo(txtTipo.getText()) == false)
                                            {
                                                OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                                                txtTipo.setText("");
                                            }
                                            else
                                            {
                                                jPanel2.setVisible(true);
                                                Desaparecer();
                                                
                                                for(int i = 0; i < 8; i++)
                                                {
                                                    JFileChooser archivo = new JFileChooser();
                                                    int opcion = archivo.showOpenDialog(this);
                                                    if(opcion == JFileChooser.APPROVE_OPTION)
                                                        textFields.get(i).setText(archivo.getSelectedFile().getAbsolutePath());
                                                }
                                                
                                                resp = CONTROL.Actualizar(id, txtNombreS.getText(), nombreAnt, txtDuracion.getText(), Double.parseDouble(txtCosto.getText()), Integer.parseInt(txtDescuento.getText()), txtTipo.getText(), txtRuta1.getText(), txtRuta2.getText(), txtRuta3.getText(), txtRuta4.getText(), txtRuta5.getText(), txtRuta6.getText(), txtRuta7.getText(), txtRuta8.getText());
                                                if(resp.equals("OK"))
                                                {
                                                    OptionPane.showMessage("Editar", "Servicio actualizado correctamente",  "/img/iconos/Info.png");
                                                    Llenar();
                                                    dispose();
                                                }
                                                else
                                                    OptionPane.showMessage("Editar","Hubo un error en la actualización",  "/img/iconos/Close.png");
                                                
                                                jPanel2.setVisible(false);
                                                Aparecer();
                                                Llenar();
                                            }
                                        else
                                            OptionPane.showMessage("Añadir Servicios", "Debes escribir el tipo al que pertenece el servicio",  "/img/iconos/Close.png");         
                                else
                                    OptionPane.showMessage("Añadir Servicios", "Debes escribir el descuento del servicio",  "/img/iconos/Close.png");       
                        else
                            OptionPane.showMessage("Añadir Servicios", "Debes escribir el costo del servicio", "/img/iconos/Close.png");
                else
                    OptionPane.showMessage("Añadir Servicios", "Debes escribir la duración del servicio",  "/img/iconos/Close.png");
        else
            OptionPane.showMessage("Añadir Servicios", "Debes escribir un nombre para el servicio",  "/img/iconos/Close.png");
    }//GEN-LAST:event_btnEditarCarrMouseClicked

    private void txtRuta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta1ActionPerformed

    private void txtRuta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta1MouseClicked

    private void txtRuta1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta1FocusLost

    private void txtRuta1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta1FocusGained

    private void txtRuta2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta2FocusGained

    private void txtRuta2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta2FocusLost

    private void txtRuta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta2MouseClicked

    private void txtRuta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta2ActionPerformed

    private void txtRuta3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta3FocusGained

    private void txtRuta3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta3FocusLost

    private void txtRuta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta3MouseClicked

    private void txtRuta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta3ActionPerformed

    private void txtRuta4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta4FocusGained

    private void txtRuta4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta4FocusLost

    private void txtRuta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta4MouseClicked

    private void txtRuta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta4ActionPerformed

    private void txtRuta5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta5FocusGained

    private void txtRuta5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta5FocusLost

    private void txtRuta5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta5MouseClicked

    private void txtRuta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta5ActionPerformed

    private void txtRuta6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta6FocusGained

    private void txtRuta6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta6FocusLost

    private void txtRuta6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta6MouseClicked

    private void txtRuta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta6ActionPerformed

    private void txtRuta7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta7FocusGained

    private void txtRuta7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta7FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta7FocusLost

    private void txtRuta7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta7MouseClicked

    private void txtRuta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta7ActionPerformed

    private void txtRuta8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta8FocusGained

    private void txtRuta8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuta8FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta8FocusLost

    private void txtRuta8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuta8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta8MouseClicked

    private void txtRuta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuta8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuta8ActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        NuevoServicio obn = new NuevoServicio();
        String resp;
        MessageDialog OptionPane = new MessageDialog(this);
              
        if(!txtNombreS.getText().isEmpty() && !txtNombreS.getText().equals("Nombre"))
            if(obn.validarNombre(txtNombreS.getText()) == false)
            {
                OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                txtNombreS.setText("");
            }
            else
                if(!txtDuracion.getText().isEmpty() && !txtDuracion.getText().equals("Duración"))
                    if(obn.validarDuracion(txtDuracion.getText()) == false)
                    {
                        OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                        txtDuracion.setText("");
                    }
                    else
                        if(!txtCosto.getText().isEmpty() && !txtCosto.getText().equals("Costo"))
                                if(!txtDescuento.getText().isEmpty() && !txtDescuento.getText().equals("Descuento"))
                                    if(obn.validarDescuento(txtDescuento.getText()) == false)
                                    {
                                        OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                                        txtDescuento.setText("");
                                    }
                                    else
                                        if(!txtTipo.getText().isEmpty() && !txtTipo.getText().equals("Tipo"))
                                            if(obn.validarTipo(txtTipo.getText()) == false)
                                            {
                                                OptionPane.showMessage("Añadir Servicios", obn.Mensaje(), "/img/iconos/Close.png");
                                                txtTipo.setText("");
                                            }
                                            else
                                            {
                                                resp = CONTROL.Actualizar(id, txtNombreS.getText(), nombreAnt, txtDuracion.getText(), Double.parseDouble(txtCosto.getText()), Integer.parseInt(txtDescuento.getText()), txtTipo.getText(), txtRuta1.getText(), txtRuta2.getText(), txtRuta3.getText(), txtRuta4.getText(), txtRuta5.getText(), txtRuta6.getText(), txtRuta7.getText(), txtRuta8.getText());
                                                if(resp.equals("OK"))
                                                {
                                                    OptionPane.showMessage("Editar", "Servicio actualizado correctamente", "/img/iconos/Info.png");
                                                    Llenar();
                                                    dispose();
                                                }
                                                else
                                                    OptionPane.showMessage("Editar", "Hubo un error en la actualización", "/img/iconos/Close.png");
                                            }
                                        else
                                            OptionPane.showMessage("Añadir Servicios", "Debes escribir el tipo al que pertenece el servicio", "/img/iconos/Close.png");         
                                else
                                    OptionPane.showMessage("Añadir Servicios", "Debes escribir el descuento del servicio", "/img/iconos/Close.png");       
                        else
                            OptionPane.showMessage("Añadir Servicios", "Debes escribir el costo del servicio", "/img/iconos/Close.png");
                else
                    OptionPane.showMessage("Añadir Servicios", "Debes escribir la duración del servicio", "/img/iconos/Close.png");
        else
            OptionPane.showMessage("Añadir Servicios", "Debes escribir un nombre para el servicio", "/img/iconos/Close.png");
    }//GEN-LAST:event_btnGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }
    
    public void Rutas(String texto)
    {
        List<String[]> rutas = CONTROL.Imagen(texto);
        String[] rutasServicio = rutas.get(0);
        txtRuta1.setText(rutasServicio[0]);
        txtRuta2.setText(rutasServicio[1]);
        txtRuta3.setText(rutasServicio[2]);
        txtRuta4.setText(rutasServicio[3]);
        txtRuta5.setText(rutasServicio[4]);
        txtRuta6.setText(rutasServicio[5]);
        txtRuta7.setText(rutasServicio[6]);
        txtRuta8.setText(rutasServicio[7]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarCarr;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombreS;
    private javax.swing.JTextField txtRuta1;
    private javax.swing.JTextField txtRuta2;
    private javax.swing.JTextField txtRuta3;
    private javax.swing.JTextField txtRuta4;
    private javax.swing.JTextField txtRuta5;
    private javax.swing.JTextField txtRuta6;
    private javax.swing.JTextField txtRuta7;
    private javax.swing.JTextField txtRuta8;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
