package vista;

import java.awt.Color;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javaswingdev.message.MessageDialog;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import libreriaproyecto.Registrarse;
import negocio.EmpleadosControl;

public class EditarEmp extends javax.swing.JFrame 
{
    private int id;
    private String nombreAnterior;
    
    private final EmpleadosControl CONTROL;
    
    public EditarEmp() 
    {
        initComponents();
        CONTROL = new EmpleadosControl();
        
        setLocation(360, 100);
    }
    
    public void Variables(int id, String nombre, String nombreAnterior, String horario, String sueldo, String imagen)
    {
        this.id = id;
        txtNombre.setText(nombre);
        this.nombreAnterior = nombreAnterior;
        txtHorario.setText(horario);
        txtSueldo.setText(sueldo);
        txtImagen.setText(imagen);
    }
    
    private void Limpiar()
    {
        txtNombre.setText("");
        txtHorario.setText("");
        txtSueldo.setText("");
        txtImagen.setText("");
    }
    
    private void Llenar()
    {
        txtNombre.setText("Nombre");
        txtHorario.setText("Horario");
        txtSueldo.setText("Sueldo");
        txtImagen.setText("Imagen");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtImagen = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(207, 189, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 920, 10));

        jLabel3.setBackground(new java.awt.Color(207, 189, 186));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 88, 88));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Editar Empleado(a)");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 110));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 120));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtNombre.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(98, 88, 88));
        txtNombre.setText("Nombre");
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 540, 45));

        txtImagen.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtImagen.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtImagen.setForeground(new java.awt.Color(98, 88, 88));
        txtImagen.setText("Imagen");
        txtImagen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtImagen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtImagenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtImagenFocusLost(evt);
            }
        });
        txtImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImagenMouseClicked(evt);
            }
        });
        txtImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagenActionPerformed(evt);
            }
        });
        jPanel1.add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 540, 45));

        txtHorario.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtHorario.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtHorario.setForeground(new java.awt.Color(98, 88, 88));
        txtHorario.setText("Horario");
        txtHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtHorario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHorarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHorarioFocusLost(evt);
            }
        });
        txtHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHorarioMouseClicked(evt);
            }
        });
        txtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 270, 45));

        txtSueldo.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtSueldo.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(98, 88, 88));
        txtSueldo.setText("Sueldo");
        txtSueldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtSueldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSueldoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSueldoFocusLost(evt);
            }
        });
        txtSueldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSueldoMouseClicked(evt);
            }
        });
        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 240, 45));

        btnCancelar.setBackground(new java.awt.Color(225, 214, 212));
        btnCancelar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(98, 88, 88));
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 190, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 920, 10));

        btnInsertar.setBackground(new java.awt.Color(225, 214, 212));
        btnInsertar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(98, 88, 88));
        btnInsertar.setText("Insertar");
        btnInsertar.setFocusPainted(false);
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        if(txtNombre.getText().equals("Nombre"))
        {
            txtNombre.setText("");
            txtNombre.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(txtNombre.getText().isEmpty())
        {
            txtNombre.setText("Nombre");
            txtNombre.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtImagenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImagenFocusGained
        if(txtImagen.getText().equals("Imagen"))
        {
            txtImagen.setForeground(new Color(98,88,88));
            JFileChooser archivo = new JFileChooser();
            int opcion = archivo.showOpenDialog(this);
            if(opcion == JFileChooser.APPROVE_OPTION)
            txtImagen.setText(archivo.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_txtImagenFocusGained

    private void txtImagenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImagenFocusLost
        if(txtImagen.getText().isEmpty())
        {
            txtImagen.setText("Imagen");
            txtImagen.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtImagenFocusLost

    private void txtImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImagenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenMouseClicked

    private void txtImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        Limpiar();
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtHorarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHorarioFocusGained
        if(txtHorario.getText().equals("Horario"))
        {
            txtHorario.setText("");
            txtHorario.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtHorarioFocusGained

    private void txtHorarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHorarioFocusLost
        if(txtHorario.getText().isEmpty())
        {
            txtHorario.setText("Horario");
            txtHorario.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtHorarioFocusLost

    private void txtHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHorarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioMouseClicked

    private void txtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioActionPerformed

    private void txtSueldoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSueldoFocusGained
        if(txtSueldo.getText().equals("Sueldo"))
        {
            txtSueldo.setText("");
            txtSueldo.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtSueldoFocusGained

    private void txtSueldoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSueldoFocusLost
        if(txtSueldo.getText().isEmpty())
        {
            txtSueldo.setText("Sueldo");
            txtSueldo.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtSueldoFocusLost

    private void txtSueldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSueldoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoMouseClicked

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        MessageDialog OptionPane = new MessageDialog(this);   
        Registrarse obr = new Registrarse();
        String resp;
        
        if(!txtNombre.getText().isEmpty() && !txtNombre.getText().equals("Nombre"))
                if(!txtHorario.getText().isEmpty() && !txtHorario.getText().equals("Horario")) 
                    if(obr.valHorario(txtHorario.getText()) == false)
                    {
                        OptionPane.showMessage("Editar Empleada(o)", "El horario no cumple con la estructura establecida 00-00", "/img/iconos/Close.png");
                        txtHorario.setText("");
                    }
                    else
                        if(!txtSueldo.getText().isEmpty() && !txtSueldo.getText().equals("Sueldo"))
                            if(obr.valSueldo(txtSueldo.getText()) == false)
                            {
                                OptionPane.showMessage("Editar Empleada(o)", obr.Mensaje(), "/img/iconos/Close.png");
                                txtSueldo.setText("");
                            }
                            else
                                if(!txtImagen.getText().isEmpty() && !txtImagen.getText().equals("Imagen"))
                                {
                                    resp = CONTROL.ActualizarD(txtNombre.getText(), nombreAnterior, txtHorario.getText(), Double.parseDouble(txtSueldo.getText()), txtImagen.getText());                                                        
                                    
                                    if(resp.equals("OK"))
                                    {
                                        OptionPane.showMessage("Editar Empleada(o)", "Inserción de Empleada(o) exitoso", "/img/iconos/Info.png");
                                        Llenar();
                                    }
                                    else
                                        OptionPane.showMessage("Editar Empleada(o)", "Hubo un error en la inserción del nuevo empleado", "/img/iconos/Close.png");
                                }                                                     
                                else
                                    OptionPane.showMessage("Editar Empleada(o)", "Debes elegir una fotografía para el nuevo empleado", "/img/iconos/Close.png");                                                        
                        else
                            OptionPane.showMessage("Editar Empleada(o)", "Debes definir un Sueldo para el nuevo empleado", "/img/iconos/Close.png");                                                
                else
                    OptionPane.showMessage("Editar Empleada(o)", "Debes definir un Horario para el nuevo empleado", "/img/iconos/Close.png");                                       
        else
            OptionPane.showMessage("Editar Empleada(o)", "Debes escribir un Nombre", "/img/iconos/Close.png");            
    }//GEN-LAST:event_btnInsertarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmp().setVisible(true);
            }
        });
    }
    
    public void Icono(ImageIcon icono, JLabel label)
    {
        Image image = icono.getImage();
        image = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        icono = new ImageIcon(image);
        label.setIcon(icono);
    }
    
    public boolean validarHorario(String horario)
    {
        String patron = "\\d{2}-\\d{2}";
        
        Pattern pattern = Pattern.compile(patron);
        Matcher matcher = pattern.matcher(horario);
        
        return matcher.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
