package vista;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URI;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class FrmAbtusClientes extends javax.swing.JFrame 
{
    Fondo fondo = new Fondo();
    
    public FrmAbtusClientes() 
    {
        setContentPane(fondo);
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        lblMenu.setIcon(new ImageIcon(getClass().getResource("/img/Fondo.png")));
        lblMenu1.setIcon(new ImageIcon(getClass().getResource("/img/Fondo.png")));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirW.png")), lblIconSalir);
        Icono(new ImageIcon(getClass().getResource("/img/principal/Lineart.png")), lblIcon);
        Icono(new ImageIcon(getClass().getResource("/img/principal/Whatsapp.png")), lblWhatsapp);
        Icono(new ImageIcon(getClass().getResource("/img/principal/Facebook.png")), lblFacebook);
        Icono(new ImageIcon(getClass().getResource("/img/principal/Instagram.png")), lblInstagram);
        Icono(new ImageIcon(getClass().getResource("/img/principal/log.png")), lblLogo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JLabel();
        lblIconSalir = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblMenu1 = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        lblTexto4 = new javax.swing.JLabel();
        lblTexto5 = new javax.swing.JLabel();
        lblTitulos = new javax.swing.JLabel();
        lblTitulos2 = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblHorario1 = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblWhatsapp = new javax.swing.JLabel();
        lblFacebook = new javax.swing.JLabel();
        lblInstagram = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2736, 50));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSalirMouseReleased(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 160, 60));
        getContentPane().add(lblIconSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 5, 60, 50));

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setText("Salir");
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 9, -1, 50));

        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMenu.setPreferredSize(new java.awt.Dimension(2736, 50));
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2300, 60));

        lblMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMenu1.setPreferredSize(new java.awt.Dimension(2736, 50));
        getContentPane().add(lblMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 60));

        lblTexto1.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        lblTexto1.setText("ayudarte a lucir y sentirte mejor.");
        getContentPane().add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 590, 40));

        lblTexto2.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        lblTexto2.setText("DE LUNES A SÁBADO");
        getContentPane().add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, 300, 40));

        lblTexto3.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        lblTexto3.setText("DE 3:00 P.M. A 8:00 P.M.");
        getContentPane().add(lblTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 400, 40));

        lblTexto4.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        lblTexto4.setText("Somos un equipo de expertos en");
        getContentPane().add(lblTexto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 590, 40));

        lblTexto5.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        lblTexto5.setText("belleza donde nos dedicamos a");
        getContentPane().add(lblTexto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 590, 40));

        lblTitulos.setFont(new java.awt.Font("Consolas", 1, 65)); // NOI18N
        lblTitulos.setForeground(new java.awt.Color(98, 88, 88));
        lblTitulos.setText("STAY FASHION!");
        getContentPane().add(lblTitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 470, 80));

        lblTitulos2.setFont(new java.awt.Font("Consolas", 1, 65)); // NOI18N
        lblTitulos2.setForeground(new java.awt.Color(98, 88, 88));
        lblTitulos2.setText("¡BIENVENIDO A");
        getContentPane().add(lblTitulos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 470, 90));

        lblHorario.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblHorario.setText("HORARIOS:");
        getContentPane().add(lblHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 160, 40));

        lblHorario1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblHorario1.setForeground(new java.awt.Color(193, 175, 170));
        lblHorario1.setText("Zaragoza 528, Sahuayo, Mich.");
        getContentPane().add(lblHorario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 740, 270, 40));
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 220, 230));

        lblWhatsapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblWhatsapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWhatsappMouseClicked(evt);
            }
        });
        getContentPane().add(lblWhatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 740, 50, 40));

        lblFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacebookMouseClicked(evt);
            }
        });
        getContentPane().add(lblFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1195, 740, 50, 40));

        lblInstagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInstagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInstagramMouseClicked(evt);
            }
        });
        getContentPane().add(lblInstagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 740, 50, 40));

        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 735, 60, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 2, true));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 730, 580, 60));

        jLabel1.setBackground(new java.awt.Color(193, 175, 170, 170));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 152, 147), 2, true));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 650, 210));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 2, true));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 650, 680));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 2, true));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 580, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        PrinCliente obd = new PrinCliente();
        obd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        btnSalir.setBorder(BorderFactory.createLoweredBevelBorder());
        lblSalir.setForeground(new Color(98, 88, 88));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirB.png")), lblIconSalir);
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseReleased
        btnSalir.setBorder(null);
        lblSalir.setForeground(new Color(255, 255, 255));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirW.png")), lblIconSalir);
    }//GEN-LAST:event_btnSalirMouseReleased

    private void lblWhatsappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWhatsappMouseClicked
        Whatsapp();
    }//GEN-LAST:event_lblWhatsappMouseClicked

    private void lblFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacebookMouseClicked
        Facebook();
    }//GEN-LAST:event_lblFacebookMouseClicked

    private void lblInstagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstagramMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInstagramMouseClicked

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAbtusClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAbtusClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAbtusClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAbtusClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAbtusClientes().setVisible(true);
            }
        });
    }
    
    public void Whatsapp() 
    {
        try 
        {
            // Número de teléfono al que se enviará el mensaje
            String phoneNumber = "3531055090";
            // Mensaje que se enviará
            String message = "¡Hola!";
            // URL para abrir WhatsApp y comenzar la conversación
            String url = "https://api.whatsapp.com/send?phone=" + phoneNumber + "&text=" + message;
            // Abre la URL en el navegador predeterminado
            Desktop.getDesktop().browse(new URI(url));
        }
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
    
    public void Facebook() 
    {
        try 
        {
            // ID o nombre de usuario del perfil de Facebook
            String profileId = "yurianaibarragranados";
            // URL para abrir el perfil de Facebook
            String url = "https://www.facebook.com/" + profileId;
            // Abre la URL en el navegador predeterminado
            Desktop.getDesktop().browse(new URI(url));
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
    
    public void Icono(ImageIcon icono, JLabel label)
    {
        Image image = icono.getImage();
        image = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        icono = new ImageIcon(image);
        label.setIcon(icono);
    }
    
    class Fondo extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/img/Fondo_men.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblHorario1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIconSalir;
    private javax.swing.JLabel lblInstagram;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JLabel lblTexto4;
    private javax.swing.JLabel lblTexto5;
    private javax.swing.JLabel lblTitulos;
    private javax.swing.JLabel lblTitulos2;
    private javax.swing.JLabel lblWhatsapp;
    // End of variables declaration//GEN-END:variables
}
