package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javaswingdev.message.MessageDialog;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import negocio.CitasControl;
import negocio.ClientesControl;

public class FrmCadrClientes extends javax.swing.JFrame 
{
    String datos[] = new String[5];
    ClientesControl CONTROL;
    CitasControl CONTROLCIT;
    Fondo fondo = new Fondo();
    
    public FrmCadrClientes() 
    {
        setContentPane(fondo);
        initComponents();
        CONTROL = new ClientesControl();
        CONTROLCIT = new CitasControl();
        
        setExtendedState(MAXIMIZED_BOTH);
        lblMenu.setIcon(new ImageIcon(getClass().getResource("/img/Fondo.png")));
        lblMenu1.setIcon(new ImageIcon(getClass().getResource("/img/Fondo.png")));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirW.png")), lblIconSalir);
        Invisible();
        btnRegresar.setVisible(false);
    }
    
    public void Listar(int idCliente)
    {
        tblFechas.setModel(CONTROLCIT.Fechas(idCliente));
    }
    
    public void Invisible()
    {
        tabla.setVisible(false);
        btnDetalles.setVisible(false);
        txtId.setVisible(false);
        lblNota.setVisible(false);
        pnlFondo2.setVisible(false);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JLabel();
        lblIconSalir = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblMenu1 = new javax.swing.JLabel();
        lblTitulos2 = new javax.swing.JLabel();
        lblNota = new javax.swing.JLabel();
        btnElegir = new javax.swing.JButton();
        cmpCalendar = new rojeru_san.componentes.RSCalendar();
        txtCliente = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnDetalles = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnObtCitas = new javax.swing.JButton();
        tabla = new javax.swing.JScrollPane();
        tblFechas = new rojeru_san.complementos.RSTableMetro();
        pnlFondo2 = new javax.swing.JPanel();
        txtDurCita = new javax.swing.JTextField();
        txtFecCita = new javax.swing.JTextField();
        txtHorCita = new javax.swing.JTextField();
        lblNota1 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2736, 50));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSalirMouseReleased(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 160, 60));
        getContentPane().add(lblIconSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 5, 60, 50));

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setText("Salir");
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 9, -1, 50));

        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMenu.setPreferredSize(new java.awt.Dimension(2736, 50));
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2300, 60));

        lblMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMenu1.setPreferredSize(new java.awt.Dimension(2736, 50));
        getContentPane().add(lblMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 60));

        lblTitulos2.setFont(new java.awt.Font("Consolas", 1, 65)); // NOI18N
        lblTitulos2.setForeground(new java.awt.Color(98, 88, 88));
        lblTitulos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulos2.setText("CITAS");
        getContentPane().add(lblTitulos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 470, 70));

        lblNota.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblNota.setForeground(new java.awt.Color(98, 88, 88));
        lblNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNota.setText("ID DE CITA:");
        getContentPane().add(lblNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 265, 250, 40));

        btnElegir.setBackground(new java.awt.Color(225, 214, 212));
        btnElegir.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnElegir.setForeground(new java.awt.Color(98, 88, 88));
        btnElegir.setText("Elegir Nueva Fecha");
        btnElegir.setFocusPainted(false);
        btnElegir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnElegirMouseClicked(evt);
            }
        });
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });
        getContentPane().add(btnElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 750, 220, 40));

        cmpCalendar.setAltoFilas(90);
        cmpCalendar.setAltoHead(90);
        cmpCalendar.setColorBackground(new java.awt.Color(225, 214, 212));
        cmpCalendar.setColorButtonHover(new java.awt.Color(98, 88, 88));
        cmpCalendar.setColorForeground(new java.awt.Color(57, 46, 46));
        cmpCalendar.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        cmpCalendar.setFuenteFilas(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        cmpCalendar.setFuenteHead(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        getContentPane().add(cmpCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 690, 730));

        txtCliente.setBackground(new java.awt.Color(191, 166, 161, 90));
        txtCliente.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(98, 88, 88));
        txtCliente.setText("Nombre de Cliente");
        txtCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212)));
        txtCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteFocusLost(evt);
            }
        });
        txtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClienteMouseClicked(evt);
            }
        });
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 350, 550, 50));

        txtId.setBackground(new java.awt.Color(255, 255, 255, 110));
        txtId.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(98, 88, 88));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setText("Id Cita");
        txtId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212)));
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 80, 50));

        btnDetalles.setBackground(new java.awt.Color(225, 214, 212));
        btnDetalles.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnDetalles.setForeground(new java.awt.Color(98, 88, 88));
        btnDetalles.setText("Obtener Detalles de Cita");
        btnDetalles.setFocusPainted(false);
        btnDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetallesMouseClicked(evt);
            }
        });
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 300, 40));

        btnModificar.setBackground(new java.awt.Color(225, 214, 212));
        btnModificar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(98, 88, 88));
        btnModificar.setText("Modificar Cita");
        btnModificar.setFocusPainted(false);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 760, 190, 40));

        btnEliminar.setBackground(new java.awt.Color(225, 214, 212));
        btnEliminar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(98, 88, 88));
        btnEliminar.setText("Eliminar Cita");
        btnEliminar.setFocusPainted(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 760, 190, 40));

        btnRegresar.setBackground(new java.awt.Color(225, 214, 212));
        btnRegresar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(98, 88, 88));
        btnRegresar.setText("Regresar");
        btnRegresar.setFocusPainted(false);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 760, 130, 40));

        btnObtCitas.setBackground(new java.awt.Color(225, 214, 212));
        btnObtCitas.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnObtCitas.setForeground(new java.awt.Color(98, 88, 88));
        btnObtCitas.setText("Obtener Citas");
        btnObtCitas.setFocusPainted(false);
        btnObtCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObtCitasMouseClicked(evt);
            }
        });
        btnObtCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtCitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnObtCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 190, 40));

        tblFechas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblFechas.setColorBackgoundHead(new java.awt.Color(225, 214, 212));
        tblFechas.setColorBordeFilas(new java.awt.Color(98, 88, 88));
        tblFechas.setColorBordeHead(new java.awt.Color(98, 88, 88));
        tblFechas.setColorFilasBackgound2(new java.awt.Color(225, 214, 212));
        tblFechas.setColorFilasForeground1(new java.awt.Color(67, 63, 63));
        tblFechas.setColorFilasForeground2(new java.awt.Color(67, 63, 63));
        tblFechas.setColorForegroundHead(new java.awt.Color(67, 63, 63));
        tblFechas.setColorSelBackgound(new java.awt.Color(208, 195, 195));
        tblFechas.setColorSelForeground(new java.awt.Color(0, 0, 0));
        tblFechas.setFuenteFilas(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        tblFechas.setFuenteFilasSelect(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        tblFechas.setFuenteHead(new java.awt.Font("Consolas", 1, 23)); // NOI18N
        tblFechas.setGridColor(new java.awt.Color(255, 255, 255));
        tblFechas.setRowHeight(30);
        tblFechas.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tabla.setViewportView(tblFechas);

        getContentPane().add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 540, 180));

        pnlFondo2.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDurCita.setBackground(new java.awt.Color(191, 166, 161, 90));
        txtDurCita.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtDurCita.setForeground(new java.awt.Color(98, 88, 88));
        txtDurCita.setText("Duración Cita");
        txtDurCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212)));
        txtDurCita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDurCitaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDurCitaFocusLost(evt);
            }
        });
        txtDurCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDurCitaMouseClicked(evt);
            }
        });
        txtDurCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurCitaActionPerformed(evt);
            }
        });
        pnlFondo2.add(txtDurCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 150, 50));

        txtFecCita.setBackground(new java.awt.Color(191, 166, 161, 90));
        txtFecCita.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtFecCita.setForeground(new java.awt.Color(98, 88, 88));
        txtFecCita.setText("Fecha Cita");
        txtFecCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212)));
        txtFecCita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFecCitaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFecCitaFocusLost(evt);
            }
        });
        txtFecCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFecCitaMouseClicked(evt);
            }
        });
        txtFecCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecCitaActionPerformed(evt);
            }
        });
        pnlFondo2.add(txtFecCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 50));

        txtHorCita.setBackground(new java.awt.Color(191, 166, 161, 90));
        txtHorCita.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtHorCita.setForeground(new java.awt.Color(98, 88, 88));
        txtHorCita.setText("Hora Cita");
        txtHorCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212)));
        txtHorCita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHorCitaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHorCitaFocusLost(evt);
            }
        });
        txtHorCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHorCitaMouseClicked(evt);
            }
        });
        txtHorCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorCitaActionPerformed(evt);
            }
        });
        pnlFondo2.add(txtHorCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 150, 50));

        lblNota1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblNota1.setForeground(new java.awt.Color(98, 88, 88));
        lblNota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNota1.setText("Duración Cita:");
        pnlFondo2.add(lblNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 15, 130, 30));

        txtObservaciones.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(98, 88, 88));
        txtObservaciones.setText("Observaciones");
        txtObservaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212), new java.awt.Color(225, 214, 212)));
        txtObservaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtObservacionesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObservacionesFocusLost(evt);
            }
        });
        pnlFondo2.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 550, 150));

        getContentPane().add(pnlFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 395, 620, 340));

        jLabel1.setBackground(new java.awt.Color(191, 166, 161, 90));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 152, 147), 2, true));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 680, 90));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 2, true));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 680, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        PrinCliente obd = new PrinCliente();
        obd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        btnSalir.setBorder(BorderFactory.createLoweredBevelBorder());
        lblSalir.setForeground(new Color(98, 88, 88));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirB.png")), lblIconSalir);
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseReleased
        btnSalir.setBorder(null);
        lblSalir.setForeground(new Color(255, 255, 255));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirW.png")), lblIconSalir);
    }//GEN-LAST:event_btnSalirMouseReleased

    private void btnDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseClicked
    }//GEN-LAST:event_btnDetallesMouseClicked

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        MessageDialog OptionPane = new MessageDialog(this);
        
        if(tblFechas.getSelectedRowCount() == 1)
        {
            btnDetalles.setVisible(false);
            lblNota.setVisible(true);
            txtId.setVisible(true);
            btnModificar.setVisible(true);
            btnEliminar.setVisible(true);
            btnRegresar.setVisible(true);
            String fecha = String.valueOf(tblFechas.getValueAt(tblFechas.getSelectedRow(), 0));
            tabla.setVisible(false);
            pnlFondo2.setVisible(true);
            
            datos = CONTROLCIT.Datos(CONTROL.GetId(txtCliente.getText()), fecha);
            
            txtFecCita.setText(fecha);
            txtId.setText(datos[0]);
            txtHorCita.setText(datos[1]);
            txtDurCita.setText(datos[2]);
            txtObservaciones.setText(datos[3]);
            txtId.setEditable(false);
            txtCliente.setEditable(false);
            txtDurCita.setEditable(false);
        }   
        else
            OptionPane.showMessage("Detalle de Cita", "Debes seleccionar una fecha de la tabla", "/img/iconos/Close.png");
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void txtClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusGained
        if(txtCliente.getText().equals("Nombre de Cliente"))
        {
            txtCliente.setText("");
            txtCliente.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtClienteFocusGained

    private void txtClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusLost
        if(txtCliente.getText().isEmpty())
        {
            txtCliente.setText("Nombre de Cliente");
            txtCliente.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtClienteFocusLost

    private void txtClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClienteMouseClicked
    }//GEN-LAST:event_txtClienteMouseClicked

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        MessageDialog OptionPane = new MessageDialog(this);
        String obs;
        String resp;
        
        if(!txtFecCita.getText().isEmpty() && !txtFecCita.getText().equals("Fecha Cita"))
            if(!txtHorCita.getText().isEmpty() && !txtHorCita.getText().equals("Hora Cita"))
                if(validarFormatoHora(txtHorCita.getText()))
                {
                    if(!txtObservaciones.getText().isBlank() && !txtObservaciones.getText().equals("Observaciones"))
                        obs = txtObservaciones.getText();
                    else
                        obs = "";
                    
                    resp = CONTROLCIT.Actualizar(Integer.parseInt(txtId.getText()), txtFecCita.getText(), txtHorCita.getText(), obs);
                    
                    if(resp.equals("OK"))
                    {
                        Invisible();
                        Listar(CONTROL.GetId(txtCliente.getText()));
                        tabla.setVisible(true);
                        btnDetalles.setVisible(true);
                        OptionPane.showMessage("Modificar Cita", "Cita modificada con éxito", "/img/iconos/Info.png");
                    }
                    else
                        if(resp.equals("Fecha Ocupada"))
                            OptionPane.showMessage("Modificar Cita", "Esa fecha ya se encuentra reservada", "/img/iconos/Close.png");                            
                        else
                            OptionPane.showMessage("Modificar Cita", "Hubo un error en la modificación de la cita", "/img/iconos/Close.png");
                }
                else
                    OptionPane.showMessage("Modificar Cita", "Error en la estructura de dato 00:00", "/img/iconos/Close.png");
            else
                OptionPane.showMessage("Modificar Cita", "Debes escribir una hora para la cita", "/img/iconos/Close.png");                
        else
            OptionPane.showMessage("Modificar Cita", "Debes escribir una fecha para la cita", "/img/iconos/Close.png");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        MessageDialog OptionPane = new MessageDialog(this);

        boolean resp;
        
        resp = CONTROLCIT.Borrar(Integer.parseInt(txtId.getText()));
        
        if(resp == true)
        {
            Invisible();
            btnRegresar.setVisible(false);
            btnObtCitas.setVisible(true);
            txtCliente.setEditable(true);    
            Listar(CONTROL.GetId(txtCliente.getText()));
            OptionPane.showMessage("Eliminar Cita", "Cita eliminada exitosamente", "/img/iconos/Info.png");
        }
        else
            OptionPane.showMessage("Eliminar Cita", "Ocurrió un error en la eliminación de la cita", "/img/iconos/Close.png");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
    }//GEN-LAST:event_txtIdFocusGained

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    }//GEN-LAST:event_txtIdFocusLost

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
    }//GEN-LAST:event_txtIdMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnObtCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObtCitasMouseClicked
    }//GEN-LAST:event_btnObtCitasMouseClicked

    private void btnObtCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtCitasActionPerformed
        MessageDialog OptionPane = new MessageDialog(this);

        if(!txtCliente.getText().isEmpty() && !txtCliente.getText().equals("Nombre de Cliente"))
            if(CONTROL.Existe(txtCliente.getText()) == true)
                if(CONTROL.TenerCitas(CONTROL.GetId(txtCliente.getText()), txtCliente.getText()))
                {
                    btnObtCitas.setVisible(false);
                    btnDetalles.setVisible(true);
                    tabla.setVisible(true);
                    Listar(CONTROL.GetId(txtCliente.getText()));
                }
                else
                    OptionPane.showMessage("Obtener Citas", "El cliente no tiene citas registradas", "/img/iconos/Close.png");                                          
            else
                OptionPane.showMessage("Obtener Citas", "Debes escribir un Nombre de Cliente que se encuentre registrado en el sistema", "/img/iconos/Close.png");                           
        else
            OptionPane.showMessage("Obtener Citas", "Debes escribir un Nombre de Cliente", "/img/iconos/Close.png");            
    }//GEN-LAST:event_btnObtCitasActionPerformed

    private void txtDurCitaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDurCitaFocusGained
    }//GEN-LAST:event_txtDurCitaFocusGained

    private void txtDurCitaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDurCitaFocusLost
    }//GEN-LAST:event_txtDurCitaFocusLost

    private void txtDurCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDurCitaMouseClicked
    }//GEN-LAST:event_txtDurCitaMouseClicked

    private void txtDurCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurCitaActionPerformed
    }//GEN-LAST:event_txtDurCitaActionPerformed

    private void txtFecCitaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecCitaFocusGained
        if(txtFecCita.getText().equals("Fecha Cita"))
        {
            txtFecCita.setText("");
            txtFecCita.setForeground(new Color(98,88,88));
        } 
    }//GEN-LAST:event_txtFecCitaFocusGained

    private void txtFecCitaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecCitaFocusLost
        if(txtFecCita.getText().isEmpty())
        {
            txtFecCita.setText("Fecha Cita");
            txtFecCita.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtFecCitaFocusLost

    private void txtFecCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFecCitaMouseClicked
    }//GEN-LAST:event_txtFecCitaMouseClicked

    private void txtFecCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecCitaActionPerformed
    }//GEN-LAST:event_txtFecCitaActionPerformed

    private void txtHorCitaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHorCitaFocusGained
        if(txtHorCita.getText().equals("Hora Cita"))
        {
            txtHorCita.setText("");
            txtHorCita.setForeground(new Color(98,88,88));
        } 
    }//GEN-LAST:event_txtHorCitaFocusGained

    private void txtHorCitaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHorCitaFocusLost
        if(txtHorCita.getText().isEmpty())
        {
            txtHorCita.setText("Hora Cita");
            txtHorCita.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtHorCitaFocusLost

    private void txtHorCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHorCitaMouseClicked
    }//GEN-LAST:event_txtHorCitaMouseClicked

    private void txtHorCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorCitaActionPerformed
    }//GEN-LAST:event_txtHorCitaActionPerformed

    private void txtObservacionesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObservacionesFocusGained
        if(txtObservaciones.getText().equals("Observaciones"))
        {
            txtObservaciones.setText("");
            txtObservaciones.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtObservacionesFocusGained

    private void txtObservacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObservacionesFocusLost
        if(txtObservaciones.getText().isEmpty())
        {
            txtObservaciones.setText("Observaciones");
            txtObservaciones.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtObservacionesFocusLost

    private void btnElegirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElegirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElegirMouseClicked

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        MessageDialog OptionPane = new MessageDialog(this);
        Calendar fechaActual = Calendar.getInstance();
        Date fecha = cmpCalendar.getDatoFecha();
        
        if(fecha != null)
        {
            Calendar fechaSeleccionadaCalendar = Calendar.getInstance();
            fechaSeleccionadaCalendar.setTime(fecha);
            if(fechaSeleccionadaCalendar.after(fechaActual))
                txtFecCita.setText(convertirFecha(String.valueOf(cmpCalendar.getDatoFecha())));
            else
                OptionPane.showMessage("Modificar Cita", "No puedes modificar la fecha de la cita a antes del día de hoy", "/img/iconos/Close.png");  
        }
        else
            OptionPane.showMessage("Modificar Cita", "Debes elegir una Fecha", "/img/iconos/Close.png");
    }//GEN-LAST:event_btnElegirActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Invisible();
        btnObtCitas.setVisible(true);
        btnRegresar.setVisible(false);
        txtCliente.setEditable(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadrClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadrClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadrClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadrClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadrClientes().setVisible(true);
            }
        });
    }
    
    public boolean validarFormatoHora(String hora) 
    {
        String formatoHora = "HH:mm";

        try 
        {
            SimpleDateFormat sdf = new SimpleDateFormat(formatoHora);
            sdf.setLenient(false);
            sdf.parse(hora);
            return true;
        }
        catch (ParseException e) 
        {
            return false;
        }
    }
    
    public String convertirFecha(String fechaCal)
    {
        String formatoFechaEntrada = "E MMM dd HH:mm:ss zzz yyyy";
        String formatoFechaSalida = "yyyy/MM/dd";
        String fechaFormateada = "";

        SimpleDateFormat sdfEntrada = new SimpleDateFormat(formatoFechaEntrada, Locale.US);
        SimpleDateFormat sdfSalida = new SimpleDateFormat(formatoFechaSalida);

        try 
        {
            Date fecha = sdfEntrada.parse(fechaCal);
            fechaFormateada = sdfSalida.format(fecha);
        }
        catch (ParseException e) 
        {
            System.out.println("Error al analizar la fecha: " + e.getMessage());
        }
        return fechaFormateada;
    }

    
    public void Icono(ImageIcon icono, JLabel label)
    {
        Image image = icono.getImage();
        image = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        icono = new ImageIcon(image);
        label.setIcon(icono);
    }
    
    class Fondo extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/img/Fondo_men.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnObtCitas;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel btnSalir;
    private rojeru_san.componentes.RSCalendar cmpCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIconSalir;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTitulos2;
    private javax.swing.JPanel pnlFondo2;
    private javax.swing.JScrollPane tabla;
    private rojeru_san.complementos.RSTableMetro tblFechas;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDurCita;
    private javax.swing.JTextField txtFecCita;
    private javax.swing.JTextField txtHorCita;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
