package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import negocio.ServiciosControl;

public class FrmSerDueña extends javax.swing.JFrame 
{
    Fondo fondo = new Fondo();
    private final ServiciosControl CONTROL;
    String nombreAnt;
    
    public FrmSerDueña() 
    {
        setContentPane(fondo);
        initComponents();
        CONTROL = new ServiciosControl();
        Listar("");
        
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirW.png")), lblIconSalir);
        Icono(new ImageIcon(getClass().getResource("/img/iconos/NuevoW.png")), lblIconNuevo);
        Icono(new ImageIcon(getClass().getResource("/img/iconos/BorrarW.png")), lblIconEliminar);
        Icono(new ImageIcon(getClass().getResource("/img/iconos/EditarW.png")), lblIconEditar);
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void Listar(String texto)
    {
        tblServicios.setModel(CONTROL.Listar(texto));
        Tabla(tblServicios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblIconSalir = new javax.swing.JLabel();
        tablaC = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        lblIconNuevo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblIconEliminar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblIconEditar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSalirMouseReleased(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setText("Salir");
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 50));
        getContentPane().add(lblIconSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 60));

        tablaC.setBackground(new java.awt.Color(255, 255, 255));

        tblServicios.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        tblServicios.setForeground(new java.awt.Color(67, 63, 63));
        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblServicios.setRowHeight(30);
        tablaC.setViewportView(tblServicios);

        getContentPane().add(tablaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 1010, 160));

        btnNuevo.setBackground(new java.awt.Color(204, 204, 255));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevoMouseReleased(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 280, 60));

        lblNuevo.setBackground(new java.awt.Color(255, 255, 255));
        lblNuevo.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setText("Añadir");
        getContentPane().add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, 50));
        getContentPane().add(lblIconNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 70, 60));

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarMouseReleased(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 280, 60));

        lblEliminar.setBackground(new java.awt.Color(255, 255, 255));
        lblEliminar.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setText("Eliminar");
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, 50));
        getContentPane().add(lblIconEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 70, 60));

        btnEditar.setBackground(new java.awt.Color(204, 204, 255));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarMouseReleased(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 280, 60));

        lblEditar.setBackground(new java.awt.Color(255, 255, 255));
        lblEditar.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("Editar");
        getContentPane().add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 770, -1, 50));
        getContentPane().add(lblIconEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 70, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        PrinDueña obd = new PrinDueña();
        obd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        btnSalir.setBorder(BorderFactory.createLoweredBevelBorder());
        lblSalir.setForeground(new Color(98, 88, 88));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirB.png")), lblIconSalir);
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseReleased
        btnSalir.setBorder(null);
        lblSalir.setForeground(new Color(255, 255, 255));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/SalirW.png")), lblIconSalir);
    }//GEN-LAST:event_btnSalirMouseReleased

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        Nuevo obn = new Nuevo();
        obn.setVisible(true);
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMousePressed
        btnNuevo.setBorder(BorderFactory.createLoweredBevelBorder());
        lblNuevo.setForeground(new Color(98, 88, 88));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/NuevoB.png")), lblIconNuevo);
    }//GEN-LAST:event_btnNuevoMousePressed

    private void btnNuevoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseReleased
        btnNuevo.setBorder(null);
        lblNuevo.setForeground(new Color(255, 255, 255));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/NuevoW.png")), lblIconNuevo);
    }//GEN-LAST:event_btnNuevoMouseReleased

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if(tblServicios.getSelectedRowCount() == 1)
        {
            String servicio = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 0));
            if(JOptionPane.showConfirmDialog(this, "¿Desea eliminar el servicio " + servicio + "?", "Eliminar",JOptionPane.YES_NO_OPTION) == 0)
            {
                String resp = CONTROL.Borrar(servicio);
                if(resp.equals("OK"))
                {
                    JOptionPane.showMessageDialog(this, "Servicio eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                    Listar("");
                }
                else
                    JOptionPane.showMessageDialog(this, "Error al eliminar el servicio", "Eliminar", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio para eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        btnEliminar.setBorder(BorderFactory.createLoweredBevelBorder());
        lblEliminar.setForeground(new Color(98, 88, 88));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/BorrarB.png")), lblIconEliminar);
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseReleased
        btnEliminar.setBorder(null);
        lblEliminar.setForeground(new Color(255, 255, 255));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/BorrarW.png")), lblIconEliminar);
    }//GEN-LAST:event_btnEliminarMouseReleased

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        Editar obe = new Editar();
        
        if(tblServicios.getSelectedRowCount() == 1)
        {
            String id = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 0));
            String nombre = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 1));
            nombreAnt = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 1));
            String duracion = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 2));
            String costo = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 3));
            String descuento = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 4));
            String tipo = String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(), 5));
            
            obe.Variables(id, nombre, nombreAnt, duracion, costo, descuento, tipo);
            obe.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio para editar", "Editar", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        btnEditar.setBorder(BorderFactory.createLoweredBevelBorder());
        lblEditar.setForeground(new Color(98, 88, 88));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/EditarB.png")), lblIconEditar);
    }//GEN-LAST:event_btnEditarMousePressed

    private void btnEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseReleased
        btnEditar.setBorder(null);
        lblEditar.setForeground(new Color(255, 255, 255));
        Icono(new ImageIcon(getClass().getResource("/img/iconos/EditarW.png")), lblIconEditar);
    }//GEN-LAST:event_btnEditarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSerDueña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSerDueña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSerDueña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSerDueña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSerDueña().setVisible(true);
            }
        });
    }
    
    public void Icono(ImageIcon icono, JLabel label)
    {
        Image image = icono.getImage();
        image = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        icono = new ImageIcon(image);
        label.setIcon(icono);
    }
    
    public void Tabla(JTable tabla)
    {
        JTableHeader theader = tabla.getTableHeader();
        theader.setBackground(Color.red);
        theader.setFont(new Font("Consolas", Font.BOLD, 20));
        theader.setForeground(new Color(67,63,63));
    }
    
    class Fondo extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/img/Fondo_dueña.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnNuevo;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblIconEditar;
    private javax.swing.JLabel lblIconEliminar;
    private javax.swing.JLabel lblIconNuevo;
    private javax.swing.JLabel lblIconSalir;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JScrollPane tablaC;
    private javax.swing.JTable tblServicios;
    // End of variables declaration//GEN-END:variables
}
