package vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import libreriaproyecto.NuevoServicio;
import negocio.ServiciosControl;

public class Nuevo extends javax.swing.JFrame 
{
    private final ServiciosControl CONTROL;
    
    public Nuevo() 
    {
        initComponents();
        CONTROL = new ServiciosControl();
        
        setLocation(360, 100);
    }
    
    private void Limpiar()
    {
        txtNombreS.setText("");
        txtDuracion.setText("");
        txtCosto.setText("");
        txtDescuento.setText("");
        txtTipo.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreS = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(207, 189, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 920, 10));

        jLabel3.setBackground(new java.awt.Color(207, 189, 186));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 88, 88));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Añadir Nuevo Servicio");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 110));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 120));

        txtNombreS.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtNombreS.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtNombreS.setForeground(new java.awt.Color(98, 88, 88));
        txtNombreS.setText("Nombre");
        txtNombreS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNombreS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreSFocusLost(evt);
            }
        });
        txtNombreS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreSMouseClicked(evt);
            }
        });
        txtNombreS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 540, 45));

        txtDuracion.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtDuracion.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtDuracion.setForeground(new java.awt.Color(98, 88, 88));
        txtDuracion.setText("Duración");
        txtDuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDuracion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDuracionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDuracionFocusLost(evt);
            }
        });
        txtDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDuracionMouseClicked(evt);
            }
        });
        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 540, 45));

        txtCosto.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtCosto.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtCosto.setForeground(new java.awt.Color(98, 88, 88));
        txtCosto.setText("Costo");
        txtCosto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCosto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCostoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCostoFocusLost(evt);
            }
        });
        txtCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCostoMouseClicked(evt);
            }
        });
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 540, 45));

        txtDescuento.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtDescuento.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(98, 88, 88));
        txtDescuento.setText("Descuento");
        txtDescuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusLost(evt);
            }
        });
        txtDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescuentoMouseClicked(evt);
            }
        });
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 540, 45));

        txtTipo.setBackground(new java.awt.Color(255, 255, 255, 180));
        txtTipo.setFont(new java.awt.Font("Consolas", 1, 19)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(98, 88, 88));
        txtTipo.setText("Tipo");
        txtTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoFocusLost(evt);
            }
        });
        txtTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTipoMouseClicked(evt);
            }
        });
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 540, 45));

        btnCancelar.setBackground(new java.awt.Color(225, 214, 212));
        btnCancelar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(98, 88, 88));
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 190, -1));

        btnNuevo.setBackground(new java.awt.Color(225, 214, 212));
        btnNuevo.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(98, 88, 88));
        btnNuevo.setText("Añadir");
        btnNuevo.setFocusPainted(false);
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 190, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 920, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreSFocusGained
        if(txtNombreS.getText().equals("Nombre"))
        {
            txtNombreS.setText("");
            txtNombreS.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtNombreSFocusGained

    private void txtNombreSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreSFocusLost
        if(txtNombreS.getText().isEmpty())
        {
            txtNombreS.setText("Nombre");
            txtNombreS.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtNombreSFocusLost

    private void txtNombreSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSMouseClicked

    private void txtNombreSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSActionPerformed

    private void txtDuracionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuracionFocusGained
        if(txtDuracion.getText().equals("Duración"))
        {
            txtDuracion.setText("");
            txtDuracion.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDuracionFocusGained

    private void txtDuracionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuracionFocusLost
        if(txtDuracion.getText().isEmpty())
        {
            txtDuracion.setText("Duración");
            txtDuracion.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDuracionFocusLost

    private void txtDuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDuracionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionMouseClicked

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void txtCostoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostoFocusGained
        if(txtCosto.getText().equals("Costo"))
        {
            txtCosto.setText("");
            txtCosto.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtCostoFocusGained

    private void txtCostoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostoFocusLost
        if(txtCosto.getText().isEmpty())
        {
            txtCosto.setText("Costo");
            txtCosto.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtCostoFocusLost

    private void txtCostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCostoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoMouseClicked

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtDescuentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusGained
        if(txtDescuento.getText().equals("Descuento"))
        {
            txtDescuento.setText("");
            txtDescuento.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDescuentoFocusGained

    private void txtDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusLost
        if(txtDescuento.getText().isEmpty())
        {
            txtDescuento.setText("Descuento");
            txtDescuento.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtDescuentoFocusLost

    private void txtDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescuentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoMouseClicked

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusGained
        if(txtTipo.getText().equals("Tipo"))
        {
            txtTipo.setText("");
            txtTipo.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtTipoFocusGained

    private void txtTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusLost
        if(txtTipo.getText().isEmpty())
        {
            txtTipo.setText("Tipo");
            txtTipo.setForeground(new Color(98,88,88));
        }
    }//GEN-LAST:event_txtTipoFocusLost

    private void txtTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoMouseClicked

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        Limpiar();
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        NuevoServicio obn = new NuevoServicio();
        String resp;
        
        if(!txtNombreS.getText().isEmpty() && !txtNombreS.getText().equals("Nombre"))
            if(obn.validarNombre(txtNombreS.getText()) == false)
            {
                JOptionPane.showMessageDialog(this, obn.Mensaje(), "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
                txtNombreS.setText("");
            }
            else
                if(!txtDuracion.getText().isEmpty() && !txtDuracion.getText().equals("Duración"))
                    if(obn.validarDuracion(txtDuracion.getText()) == false)
                    {
                        JOptionPane.showMessageDialog(this, obn.Mensaje(), "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
                        txtDuracion.setText("");
                    }
                    else
                        if(!txtCosto.getText().isEmpty() && !txtCosto.getText().equals("Costo"))
                            if(obn.validarCosto(txtCosto.getText()) == false)
                            {
                                JOptionPane.showMessageDialog(this, obn.Mensaje(), "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
                                txtCosto.setText("");
                            }
                            else
                                if(!txtDescuento.getText().isEmpty() && !txtDescuento.getText().equals("Descuento"))
                                    if(obn.validarDescuento(txtDescuento.getText()) == false)
                                    {
                                        JOptionPane.showMessageDialog(this, obn.Mensaje(), "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
                                        txtDescuento.setText("");
                                    }
                                    else
                                        if(!txtTipo.getText().isEmpty() && !txtTipo.getText().equals("Tipo"))
                                            if(obn.validarTipo(txtTipo.getText()) == false)
                                            {
                                                JOptionPane.showMessageDialog(this, obn.Mensaje(), "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
                                                txtTipo.setText("");
                                            }
                                            else
                                            {
                                                resp = CONTROL.Insertar(txtNombreS.getText(), txtDuracion.getText(), Double.parseDouble(txtCosto.getText()), Integer.parseInt(txtDescuento.getText()), txtTipo.getText());
                                                txtNombreS.setText("Nombre");
                                                txtDuracion.setText("Duración");
                                                txtCosto.setText("Costo");
                                                txtDescuento.setText("Descuento");
                                                txtTipo.setText("Tipo");
                                            }
                                        else
                                            JOptionPane.showMessageDialog(this, "Debes escribir el tipo al que pertenece el servicio", "Añadir Servicios", JOptionPane.ERROR_MESSAGE);         
                                else
                                    JOptionPane.showMessageDialog(this, "Debes escribir el descuento del servicio", "Añadir Servicios", JOptionPane.ERROR_MESSAGE);       
                        else
                            JOptionPane.showMessageDialog(this, "Debes escribir el costo del servicio", "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this, "Debes escribir la duración del servicio", "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Debes escribir un nombre para el servicio", "Añadir Servicios", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnNuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombreS;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
